# Generated by Django 3.1.7 on 2022-06-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_customer_qq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='qq',
        ),
    ]
