# Generated by Django 3.1.7 on 2022-06-07 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_country_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
